### ISSUE TITLE
GENIE bin files missing in new 2021 release

### ISSUE THREAD

**Issue by ThomasRuf** [ShipSoft/shipdist#68]
Reported by Antonio. For example, gevgen missing in $GENIE/bin/. 
change to genie.sh 28 days: Migrate to LHAPDF6 (#39). This is unlikely to be the source.

Maybe due to changes in alibuild, cmake version?

The installation script contains essentially, make install, and rsync -a bin/* $INSTALLROOT/genie/bin . 
Need to make another build with GENIE as development package, to investigate. Unfortunately, alibuild insists of also rebuilding ROOT. So, this can take awhile.

**Comment by olantwin** [comment]
I can confirm that it's also not present in the docker image, so unrelated to CVMFS.

Building GENIE as development package now.

**Comment by olantwin** [comment]
Several build targets (silently!) fail because of this error:
`/sw/slc7_x86-64/GCC-Toolchain/v7.3.0-alice2-1/bin/../lib/gcc/x86_64-unknown-linux-gnu/7.3.0/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot find -lGPDF`

**Comment by ThomasRuf** [comment]
on my local machine, i don't need GCC-Toolchain. I don't think I observed this problem on slc7. Where do you run this?

**Comment by olantwin** [comment]
CC7 (inside docker)

I believe GPDF is a GENIE library. Currently scanning through the log for more info.

**Comment by ThomasRuf** [comment]
aah, pdf sounds suspicious. Maybe it is related to the change to lhapdf, and not using anymore lhapdf5?

**Comment by olantwin** [comment]
Seems GENIE might need to be configures differently for LHAPDF6:

```
PDFLIB.cxx: In member function 'void genie::PDFLIB::SetPDFSetFromConfig() const':
PDFLIB.cxx:122:11: error: 'initPDFByName' is not a member of 'LHAPDF'
   LHAPDF::initPDFByName(name, stype, memset);
           ^~~~~~~~~~~~~
PDFLIB.cxx:122:11: note: suggested alternative: 'initPDFSetByName'
   LHAPDF::initPDFByName(name, stype, memset);
           ^~~~~~~~~~~~~
           initPDFSetByName
make[1]: *** [PDFLIB.o] Error 1
```

**Comment by ThomasRuf** [comment]
then our install script is useless. It should stop when the compilation fails. I never seen a complain about failing.

**Comment by ThomasRuf** [comment]
I am afraid our GENIE can only work with the fortran version. Maybe we need also to upgrade to more recent GENIE?

**Comment by olantwin** [comment]
Yes, it should not fail silently. 

Looking at the documentation and repository, I see no indication that GENIE (even the most recent version) can use LHAPDF5 directly. It is mentioned however that PDFs from LHAPDF6 can be used. How important is the direct LHAPDF integration?

**Comment by olantwin** [comment]
We should probably upgrade anyway, as the version we use is three and a half years old --- at least to the most recent patch release of the major release we are using (2.12.10 vs. 2.12.6). The most recent release in general is now 3.00.06

**Comment by olantwin** [comment]
I can't figure out why the error's are completely silent. The exit status of make seems to be 0.

**Comment by ThomasRuf** [comment]
Know idea about the importance of the LHAPDF integration. Haven't worked with GENIE for a long time

**Comment by ThomasRuf** [comment]
had a quick look at https://github.com/GENIE-MC/Generator. Looks very much different compared to what we have.

**Comment by antonioiuliano2** [comment]
I agree with you that GENIE has been updated a lot and we should follow it.

My only concern is that, whenever we update the version, we should advertise the change to the FairShip user community.

Genie manual recommends to use the input cross section splines for the same version of GENIE you use for the simulations, so the splines should be re-downloaded (or generated again with "gmkspl"). Annarita may know more about how it works.

**Comment by ThomasRuf** [comment]
Generating new splines takes a few hours if I remember correctly. The version of GENIE which we currently use is more than 5 years old. It might be a good idea to make a change now. Looking at the supplier web page: http://releases.genie-mc.org/ , the version to use would be 3.0.6, with support for LHAPDF6. Maybe Antonio could start to read the manual how to use it, and Oliver and me have a look how to compile it for FairShip.

**Comment by ThomasRuf** [comment]
Reading latest user manual https://genie-docdb.pp.rl.ac.uk/DocDB/0000/000002/006/man.pdf, Appendix B about installation, it still seems to require lhapdf5 and pythia6. So, if this is anyhow needed, we should first go back to also install lhapdf5, which would allow to use the old version of Genie for awhile, and prepare in parallel the transition to the new version.

**Comment by ThomasRuf** [comment]
Compiling Genie with lhapdf5 comes up now with this error:

gtestINukeHadroXSec.cxx: In function 'int main(int, char**)':
gtestINukeHadroXSec.cxx:80:38: error: array must be initialized with a brace-enclosed initializer [-fpermissive]
   string        fatestr   [nfates] = "  ";
                                      ^~~~
gtestINukeHadroXSec.cxx:173:7: warning: case value '13' not in enumerated type 'genie::INukeFateHA_t {aka genie::EINukeFateHA_t}' [-Wswitch]
       case 13:  countfate[8]++; break;
       ^~~~
make[1]: *** [gtestINukeHadroXSec] Error 1
make[1]: Leaving directory `/media/disk1/SHiPBuild/sw/BUILD/e4ca9e25444ea66014652e598cfcdeb10a3c182d/GENIE/src/validation/Intranuke'

any idea how to fix this?

**Comment by ThomasRuf** [comment]
OK, fixed it. I do have now GENIE compiled and get back all missing binaries. I will commit the changes to shipdist and GENIE, and put the libraries on cvmfs. Will take a few hours.

**Comment by antonioiuliano2** [comment]
Thank you very much, Thomas! 
Do not worry about the time, there is no hurry since for the moment I can launch the GENIE simulations from the 2020 cvmfs.

**Comment by ThomasRuf** [comment]
Please have a look at the new manual of the new version. Continuing with the old is only a temporary solution.

**Comment by antonioiuliano2** [comment]
Sure, thanks again!
